import { Poppins, Montserrat } from 'next/font/google';
import "./globals.css";
import NavBar from './Components/NavBar';

const poppins = Poppins({ weight: ['400', '500', '600', '700', '800', '900'], variable: "--font-poppins", subsets: ['latin'] })
const montserrat = Montserrat({ weight: ['400', '500', '600', '700', '800', '900'], variable: "--font-montserrat", subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserrat.variable} border-4 border-green-900 px-5 md:px-[2.5rem] lg:px-[3.125rem] xl:px-[15.625rem] text-black dark:text-white font-poppins bg-white dark:bg-[#1E1E1E]`}
      >
        <NavBar />
        {children}

      </body>
    </html>
  );
}
