import { Poppins, Montserrat } from 'next/font/google';
import "./globals.css";
import NavBar from './Components/NavBar';
import ThemeContext from './Context/ThemeContext';
import ClientThemeWrapper from './Context/ClientThemeWrapper';

const poppins = Poppins({ weight: ['400', '500', '600', '700', '800', '900'], variable: "--font-poppins", subsets: ['latin'] })
const montserrat = Montserrat({ weight: ['400', '500', '600', '700', '800', '900'], variable: "--font-montserrat", subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserrat.variable} antialiased`}
      >

        <ThemeContext>
          <ClientThemeWrapper>
            <div className='lg:mx-[70px] xl:mx-[250px] font-poppins'>
              <NavBar />
              {children}
            </div>
          </ClientThemeWrapper>
        </ThemeContext>

      </body>
    </html>
  );
}
